import { Property, LawItem } from './types'

export const properties: Property[] = [
  {
    id: 'p1',
    address: '서울시 마포구 서교동 123-4',
    buildingName: '서교 하이츠',
    type: '빌라',
    floor: '3층',
    area: 33,
    deposit: 15000,
    monthlyRent: null,
    salePrice: 22000,
    leaseRatio: 68,
    risk: '안전',
    mortgage: 3000,
    seizure: false,
    ownerTax: false,
    builtYear: 2018,
    images: ['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=600&q=80'],
    description: '마포구 중심에 위치한 깔끔한 빌라. 지하철 2호선 홍대입구역 도보 10분.',
  },
  {
    id: 'p2',
    address: '서울시 강남구 역삼동 456-7',
    buildingName: '역삼 파크뷰',
    type: '오피스텔',
    floor: '12층',
    area: 26,
    deposit: 30000,
    monthlyRent: null,
    salePrice: 35000,
    leaseRatio: 85,
    risk: '위험',
    mortgage: 18000,
    seizure: true,
    ownerTax: false,
    builtYear: 2012,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80'],
    description: '강남구 역삼동 위치. 전세가율 85% 이상으로 주의 필요.',
  },
  {
    id: 'p3',
    address: '서울시 성동구 성수동 789-1',
    buildingName: '성수 어반',
    type: '아파트',
    floor: '7층',
    area: 59,
    deposit: 40000,
    monthlyRent: null,
    salePrice: 72000,
    leaseRatio: 55,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2020,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80'],
    description: '성수동 핫플 중심. 카페거리 도보 5분. 전세가율 안전.',
  },
  {
    id: 'p4',
    address: '서울시 은평구 불광동 321-5',
    buildingName: '불광 그린빌',
    type: '빌라',
    floor: '2층',
    area: 29,
    deposit: 8000,
    monthlyRent: null,
    salePrice: 11000,
    leaseRatio: 72,
    risk: '경고',
    mortgage: 6000,
    seizure: false,
    ownerTax: true,
    builtYear: 2005,
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=80'],
    description: '은평구 불광동. 집주인 세금 체납 이력 있음. 계약 전 확인 필요.',
  },
  {
    id: 'p5',
    address: '서울시 송파구 잠실동 10-3',
    buildingName: '잠실 리버사이드',
    type: '아파트',
    floor: '15층',
    area: 84,
    deposit: 65000,
    monthlyRent: null,
    salePrice: 120000,
    leaseRatio: 54,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2015,
    images: ['https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=600&q=80'],
    description: '잠실 한강뷰 대단지 아파트. 지하철 2·8호선 잠실역 도보 5분. 전세가율 안전.',
  },
  {
    id: 'p6',
    address: '서울시 용산구 이태원동 55-2',
    buildingName: '이태원 힐탑',
    type: '빌라',
    floor: '4층',
    area: 45,
    deposit: 25000,
    monthlyRent: null,
    salePrice: 29000,
    leaseRatio: 86,
    risk: '위험',
    mortgage: 15000,
    seizure: false,
    ownerTax: true,
    builtYear: 2008,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=600&q=80'],
    description: '이태원 언덕 위 빌라. 전세가율 86%, 근저당 과다. 세금 체납 이력 있음.',
  },
  {
    id: 'p7',
    address: '서울시 관악구 신림동 88-1',
    buildingName: '신림 스카이',
    type: '원룸',
    floor: '5층',
    area: 16,
    deposit: 5000,
    monthlyRent: null,
    salePrice: 8000,
    leaseRatio: 62,
    risk: '안전',
    mortgage: 0,
    seizure: false,
    ownerTax: false,
    builtYear: 2019,
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80'],
    description: '신림역 도보 7분. 신축 원룸. 근저당 없음, 깨끗한 등기.',
  },
  {
    id: 'p8',
    address: '서울시 강서구 마곡동 200-5',
    buildingName: '마곡 더퍼스트',
    type: '오피스텔',
    floor: '8층',
    area: 33,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 24000,
    leaseRatio: 75,
    risk: '경고',
    mortgage: 8000,
    seizure: false,
    ownerTax: false,
    builtYear: 2021,
    images: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600&q=80'],
    description: '마곡나루역 도보 3분. LG사이언스파크 인근. 전세가율 75%로 경고 구간.',
  },
  {
    id: 'p9',
    address: '경기도 수원시 영통구 망포동 33-7',
    buildingName: '망포 센트럴파크',
    type: '아파트',
    floor: '11층',
    area: 59,
    deposit: 28000,
    monthlyRent: null,
    salePrice: 48000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 4000,
    seizure: false,
    ownerTax: false,
    builtYear: 2017,
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80'],
    description: '망포역 도보 5분. 대단지 아파트. 수원 영통 핵심 입지. 전세가율 안전.',
  },
  {
    id: 'p10',
    address: '경기도 성남시 분당구 정자동 100-2',
    buildingName: '정자 아이파크',
    type: '아파트',
    floor: '20층',
    area: 115,
    deposit: 80000,
    monthlyRent: null,
    salePrice: 130000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 20000,
    seizure: false,
    ownerTax: false,
    builtYear: 2003,
    images: ['https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=600&q=80'],
    description: '분당 정자역 초역세권. 넓은 평형대. 판교 테크노밸리 출퇴근 최적.',
  },
  {
    id: 'p11',
    address: '인천시 연수구 송도동 5-1',
    buildingName: '송도 더샵',
    type: '아파트',
    floor: '25층',
    area: 84,
    deposit: 35000,
    monthlyRent: null,
    salePrice: 55000,
    leaseRatio: 63,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2016,
    images: ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80'],
    description: '송도 국제업무지구 중심. 인천1호선 센트럴파크역 도보 3분.',
  },
  {
    id: 'p12',
    address: '서울시 노원구 상계동 777-3',
    buildingName: '상계 현대아파트',
    type: '아파트',
    floor: '6층',
    area: 49,
    deposit: 22000,
    monthlyRent: null,
    salePrice: 26000,
    leaseRatio: 84,
    risk: '위험',
    mortgage: 12000,
    seizure: true,
    ownerTax: false,
    builtYear: 1992,
    images: ['https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=600&q=80'],
    description: '상계역 인근 구축 아파트. 전세가율 84%, 압류 이력 있음. 계약 전 등기 확인 필수.',
  },
  {
    id: 'p13',
    address: '서울시 동작구 사당동 44-9',
    buildingName: '사당 e편한세상',
    type: '아파트',
    floor: '9층',
    area: 59,
    deposit: 32000,
    monthlyRent: null,
    salePrice: 58000,
    leaseRatio: 55,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2014,
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80'],
    description: '4호선·2호선 환승 사당역 도보 3분. 학원가 인근. 전세가율 55% 안전.',
  },
  {
    id: 'p14',
    address: '서울시 중구 신당동 22-1',
    buildingName: '신당 롯데캐슬',
    type: '아파트',
    floor: '18층',
    area: 84,
    deposit: 55000,
    monthlyRent: null,
    salePrice: 82000,
    leaseRatio: 67,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2011,
    images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80'],
    description: '2·6호선 신당역 도보 5분. 남산뷰 고층. 주변 편의시설 풍부.',
  },
  {
    id: 'p15',
    address: '서울시 강북구 미아동 13-4',
    buildingName: '미아 삼성래미안',
    type: '아파트',
    floor: '4층',
    area: 49,
    deposit: 19000,
    monthlyRent: null,
    salePrice: 22000,
    leaseRatio: 86,
    risk: '위험',
    mortgage: 9000,
    seizure: false,
    ownerTax: true,
    builtYear: 1999,
    images: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80'],
    description: '전세가율 86% 위험 구간. 집주인 세금 체납 이력 있음. 계약 시 각별한 주의 필요.',
  },
  {
    id: 'p16',
    address: '경기도 고양시 일산동구 장항동 100-1',
    buildingName: '일산 위브더제니스',
    type: '아파트',
    floor: '30층',
    area: 115,
    deposit: 45000,
    monthlyRent: null,
    salePrice: 75000,
    leaseRatio: 60,
    risk: '안전',
    mortgage: 8000,
    seizure: false,
    ownerTax: false,
    builtYear: 2010,
    images: ['https://images.unsplash.com/photo-1549517045-bc93de075e53?w=600&q=80'],
    description: '킨텍스 인근 초고층 아파트. GTX-A 킨텍스역 개통 예정. 전세가율 안전.',
  },
  {
    id: 'p17',
    address: '경기도 용인시 수지구 죽전동 55-3',
    buildingName: '죽전 푸르지오',
    type: '아파트',
    floor: '13층',
    area: 84,
    deposit: 38000,
    monthlyRent: null,
    salePrice: 62000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 6000,
    seizure: false,
    ownerTax: false,
    builtYear: 2006,
    images: ['https://images.unsplash.com/photo-1626178793926-22b28830aa30?w=600&q=80'],
    description: '신분당선 죽전역 도보 8분. 단국대학교 인근. 학군 우수.',
  },
  {
    id: 'p18',
    address: '서울시 강동구 천호동 200-7',
    buildingName: '천호 한양수자인',
    type: '오피스텔',
    floor: '10층',
    area: 29,
    deposit: 14000,
    monthlyRent: null,
    salePrice: 17000,
    leaseRatio: 82,
    risk: '위험',
    mortgage: 10000,
    seizure: true,
    ownerTax: false,
    builtYear: 2013,
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&q=80'],
    description: '5·8호선 천호역 도보 2분. 전세가율 82%, 근저당 과다, 압류 이력 있음.',
  },
  {
    id: 'p19',
    address: '부산시 해운대구 우동 33-5',
    buildingName: '해운대 아이파크',
    type: '아파트',
    floor: '22층',
    area: 130,
    deposit: 60000,
    monthlyRent: null,
    salePrice: 110000,
    leaseRatio: 54,
    risk: '안전',
    mortgage: 15000,
    seizure: false,
    ownerTax: false,
    builtYear: 2011,
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80'],
    description: '해운대 해수욕장 도보 5분. 마린시티 초고층 오션뷰. 부산 최고 입지.',
  },
  {
    id: 'p20',
    address: '대구시 수성구 범어동 77-2',
    buildingName: '범어 SK뷰',
    type: '아파트',
    floor: '16층',
    area: 84,
    deposit: 30000,
    monthlyRent: null,
    salePrice: 52000,
    leaseRatio: 57,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2009,
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=80'],
    description: '대구 최고 학군 수성구. 범어역 도보 6분. 전세가율 안전.',
  },
  {
    id: 'p21',
    address: '서울시 광진구 화양동 33-8',
    buildingName: '화양 더클래스',
    type: '오피스텔',
    floor: '9층',
    area: 30,
    deposit: 16000,
    monthlyRent: null,
    salePrice: 20000,
    leaseRatio: 80,
    risk: '위험',
    mortgage: 9000,
    seizure: false,
    ownerTax: false,
    builtYear: 2016,
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80'],
    description: '건대입구역 도보 5분. 전세가율 80% 위험 구간. 근저당 금액 확인 필요.',
  },
  {
    id: 'p22',
    address: '서울시 서대문구 연희동 55-12',
    buildingName: '연희 파크하임',
    type: '빌라',
    floor: '2층',
    area: 42,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 29000,
    leaseRatio: 62,
    risk: '안전',
    mortgage: 2000,
    seizure: false,
    ownerTax: false,
    builtYear: 2020,
    images: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80'],
    description: '연희동 조용한 주택가. 신축 빌라. 홍대·신촌 접근성 우수. 근저당 최소.',
  },
  {
    id: 'p23',
    address: '경기도 남양주시 다산동 200-3',
    buildingName: '다산 자이',
    type: '아파트',
    floor: '14층',
    area: 84,
    deposit: 32000,
    monthlyRent: null,
    salePrice: 55000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2019,
    images: ['https://images.unsplash.com/photo-1600047508788-786f3865b8f4?w=600&q=80'],
    description: '경의중앙선 도농역 도보 10분. 대단지 신축. 다산신도시 중심.',
  },
  {
    id: 'p24',
    address: '서울시 동대문구 답십리동 44-7',
    buildingName: '답십리 래미안',
    type: '아파트',
    floor: '5층',
    area: 59,
    deposit: 29000,
    monthlyRent: null,
    salePrice: 37000,
    leaseRatio: 78,
    risk: '경고',
    mortgage: 7000,
    seizure: false,
    ownerTax: false,
    builtYear: 2007,
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80'],
    description: '5호선 답십리역 도보 3분. 전세가율 78% 경고 구간.',
  },
  {
    id: 'p25',
    address: '대전시 유성구 봉명동 10-2',
    buildingName: '봉명 센트럴시티',
    type: '아파트',
    floor: '11층',
    area: 84,
    deposit: 22000,
    monthlyRent: null,
    salePrice: 38000,
    leaseRatio: 57,
    risk: '안전',
    mortgage: 4000,
    seizure: false,
    ownerTax: false,
    builtYear: 2013,
    images: ['https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=600&q=80'],
    description: '카이스트·충남대 인근. 유성온천 도보 10분. 전세가율 안전.',
  },
  {
    id: 'p26',
    address: '서울시 영등포구 당산동 88-3',
    buildingName: '당산 e편한세상',
    type: '아파트',
    floor: '8층',
    area: 59,
    deposit: 34000,
    monthlyRent: null,
    salePrice: 60000,
    leaseRatio: 56,
    risk: '안전',
    mortgage: 6000,
    seizure: false,
    ownerTax: false,
    builtYear: 2012,
    images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=80'],
    description: '2·5호선 환승 당산역 도보 4분. 여의도 업무지구 접근성 최고.',
  },
  {
    id: 'p27',
    address: '경기도 안양시 동안구 평촌동 33-1',
    buildingName: '평촌 어바인퍼스트',
    type: '아파트',
    floor: '19층',
    area: 115,
    deposit: 48000,
    monthlyRent: null,
    salePrice: 78000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2008,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=600&q=80'],
    description: '평촌 학원가 중심. 4호선 범계역 도보 5분. 학군 최우수.',
  },
  {
    id: 'p28',
    address: '서울시 강남구 개포동 111-5',
    buildingName: '개포 디에이치',
    type: '아파트',
    floor: '12층',
    area: 84,
    deposit: 90000,
    monthlyRent: null,
    salePrice: 160000,
    leaseRatio: 56,
    risk: '안전',
    mortgage: 20000,
    seizure: false,
    ownerTax: false,
    builtYear: 2022,
    images: ['https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=600&q=80'],
    description: '개포 재건축 신축. 강남권 최신 시설. 3호선 대청역 도보 7분.',
  },
  {
    id: 'p29',
    address: '서울시 금천구 시흥동 22-9',
    buildingName: '시흥 한라비발디',
    type: '아파트',
    floor: '3층',
    area: 49,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 21000,
    leaseRatio: 85,
    risk: '위험',
    mortgage: 10000,
    seizure: true,
    ownerTax: false,
    builtYear: 2001,
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80'],
    description: '전세가율 85% 위험 구간. 압류 이력 있음. 계약 전 등기부등본 필수 확인.',
  },
  {
    id: 'p30',
    address: '경기도 하남시 미사동 100-8',
    buildingName: '미사 강변 센트럴자이',
    type: '아파트',
    floor: '17층',
    area: 84,
    deposit: 40000,
    monthlyRent: null,
    salePrice: 68000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 7000,
    seizure: false,
    ownerTax: false,
    builtYear: 2018,
    images: ['https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=600&q=80'],
    description: '5호선 미사역 도보 5분. 한강뷰 대단지. 미사강변도시 핵심 입지.',
  },
]

export const laws: LawItem[] = [
  {
    id: 'l1',
    title: '전세보증금 반환 의무',
    category: '보증금',
    summary: '임대차 계약 종료 시 집주인은 보증금을 반환해야 합니다.',
    content: '임대인은 임대차 계약이 종료된 경우 임차인에게 보증금을 반환할 의무가 있습니다. 반환하지 않을 경우 임차인은 임차권등기명령을 신청하거나 보증금반환청구소송을 제기할 수 있습니다.',
    relatedLaw: '주택임대차보호법 제3조의3',
  },
  {
    id: 'l2',
    title: '전입신고 및 확정일자',
    category: '임차인',
    summary: '전입신고와 확정일자를 받으면 보증금이 법적으로 보호됩니다.',
    content: '임차인이 전입신고를 하고 확정일자를 받으면 대항력과 우선변제권이 생깁니다. 이로써 건물이 경매에 넘어가더라도 보증금을 우선 돌려받을 수 있습니다.',
    relatedLaw: '주택임대차보호법 제3조, 제3조의2',
  },
  {
    id: 'l3',
    title: '임대차 계약갱신 청구권',
    category: '계약',
    summary: '임차인은 1회에 한해 계약 갱신을 요구할 수 있습니다.',
    content: '2020년 7월 31일부터 시행된 계약갱신청구권제도에 따라 임차인은 최초 계약 만료 시 1회에 한해 2년 연장을 요구할 수 있습니다. 임대인은 정당한 사유 없이 이를 거부할 수 없습니다.',
    relatedLaw: '주택임대차보호법 제6조의3',
  },
  {
    id: 'l4',
    title: '전세가율 위험 기준',
    category: '보증금',
    summary: '전세가율 80% 이상은 깡통전세 위험 구간입니다.',
    content: '전세가율(매매가 대비 전세가 비율)이 80% 이상이면 집값 하락 시 보증금을 돌려받지 못할 위험이 있습니다. 일반적으로 70% 이하를 안전 구간으로 봅니다.',
    relatedLaw: '주택도시보증공사(HUG) 전세보증보험 기준',
  },
  {
    id: 'l5',
    title: '근저당 설정 확인',
    category: '계약',
    summary: '계약 전 등기부등본을 열람해 근저당 여부를 반드시 확인하세요.',
    content: '등기부등본의 을구에서 근저당 설정 금액을 확인할 수 있습니다. 근저당 금액 + 전세보증금이 매매가의 80%를 초과하면 위험합니다. 대법원 인터넷등기소에서 열람 가능합니다.',
    relatedLaw: '부동산등기법 제75조',
  },
  {
    id: 'l6',
    title: '임대인 세금 체납 확인',
    category: '임대인',
    summary: '집주인의 세금 체납 여부를 계약 전에 확인할 수 있습니다.',
    content: '2023년부터 임차인은 임대인의 동의 없이도 관할 세무서에서 임대인의 미납 국세 열람이 가능합니다. 세금 체납 시 국가가 보증금보다 우선 변제를 받을 수 있어 위험합니다.',
    relatedLaw: '국세징수법 제109조',
  },
  {
    id: 'l7',
    title: '전세보증보험 가입 방법',
    category: '보증금',
    summary: 'HUG 또는 SGI서울보증에서 전세보증보험에 가입하면 보증금을 보호받을 수 있습니다.',
    content: '전세보증보험은 임대차 계약 종료 후 집주인이 보증금을 반환하지 않을 경우 보증기관이 대신 지급하는 상품입니다. HUG(주택도시보증공사)와 SGI서울보증에서 가입 가능하며, 전세가율 90% 이하 매물에 한해 가입이 가능합니다. 보험료는 보증금의 약 0.1~0.4% 수준입니다.',
    relatedLaw: '주택도시기금법 제16조',
  },
  {
    id: 'l8',
    title: '묵시적 갱신',
    category: '계약',
    summary: '계약 만료 후 아무 의사 표시가 없으면 동일 조건으로 자동 연장됩니다.',
    content: '임대차 계약 만료 2개월 전까지 임대인 또는 임차인이 갱신 거절 의사를 표시하지 않으면 이전 계약과 동일한 조건으로 묵시적으로 갱신됩니다. 묵시적 갱신 후에는 임차인이 언제든지 3개월 전 통보로 계약 해지가 가능합니다.',
    relatedLaw: '주택임대차보호법 제6조',
  },
  {
    id: 'l9',
    title: '전세사기 피해자 지원',
    category: '분쟁',
    summary: '전세사기 피해자는 정부 지원 프로그램을 통해 법적·금융적 도움을 받을 수 있습니다.',
    content: '2023년 전세사기피해자 지원 및 주거안정에 관한 특별법이 시행되었습니다. 피해자는 경공매 유예, 저금리 대출, 공공임대 우선 입주 등의 혜택을 받을 수 있습니다. 지원 신청은 주거안정지원센터 또는 LH공사를 통해 가능합니다.',
    relatedLaw: '전세사기피해자 지원 및 주거안정에 관한 특별법',
  },
  {
    id: 'l10',
    title: '임차권등기명령 신청',
    category: '임차인',
    summary: '계약 종료 후 보증금을 받지 못했다면 임차권등기명령을 신청하세요.',
    content: '임대차 계약이 종료됐는데 보증금을 돌려받지 못한 경우, 임차인은 관할 법원에 임차권등기명령을 신청할 수 있습니다. 등기가 완료되면 이사를 나가더라도 대항력과 우선변제권이 유지됩니다. 신청 비용은 약 5천 원 수준입니다.',
    relatedLaw: '주택임대차보호법 제3조의3',
  },
  {
    id: 'l11',
    title: '월세 전환 시 전환율 제한',
    category: '계약',
    summary: '전세를 월세로 전환할 때 법정 전환율을 초과할 수 없습니다.',
    content: '보증금 일부를 월세로 전환할 경우, 법정 전환율(현행 연 10% 또는 한국은행 기준금리 + 2% 중 낮은 값) 이하로만 전환이 가능합니다. 이를 초과한 월세는 무효이며 초과분을 반환받을 수 있습니다.',
    relatedLaw: '주택임대차보호법 제7조의2',
  },
  {
    id: 'l12',
    title: '소액임차인 최우선변제권',
    category: '보증금',
    summary: '일정 금액 이하 보증금은 경매 시 최우선으로 변제받을 수 있습니다.',
    content: '소액임차인은 경매 낙찰가의 일정 비율에서 다른 채권자보다 우선하여 보증금 일부를 변제받을 수 있습니다. 서울 기준 보증금 1억 6,500만 원 이하 임차인은 최대 5,500만 원까지 최우선 변제됩니다. 단, 전입신고와 점유 요건을 갖춰야 합니다.',
    relatedLaw: '주택임대차보호법 제8조',
  },
  {
    id: 'l13',
    title: '임대인 동의 없는 전대차 금지',
    category: '임차인',
    summary: '집주인 동의 없이 집을 다시 세주는 것은 불법입니다.',
    content: '임차인은 임대인의 동의 없이 임차한 주택을 제3자에게 전대(재임대)할 수 없습니다. 무단 전대 시 임대인은 계약을 해지할 수 있으며, 임차인은 손해배상 책임을 질 수 있습니다.',
    relatedLaw: '민법 제629조',
  },
  {
    id: 'l14',
    title: '계약서 특약 사항 작성 요령',
    category: '계약',
    summary: '특약 사항을 꼼꼼히 기재하면 분쟁 발생 시 유리한 위치에 설 수 있습니다.',
    content: '계약서 특약란에는 수리 범위, 원상복구 기준, 보증금 반환 시기, 중도 해지 조건 등을 구체적으로 기재해야 합니다. "협의 후 결정" 같은 모호한 표현은 피하고, 날짜와 금액을 명확히 적어야 합니다. 특약은 법정 기준보다 임차인에게 유리한 내용으로 작성할 수 있습니다.',
    relatedLaw: '주택임대차보호법 제10조(강행규정)',
  },
  {
    id: 'l15',
    title: '보증금 반환 지연 시 이자 청구',
    category: '보증금',
    summary: '계약 만료 후 보증금을 늦게 돌려받으면 이자를 청구할 수 있습니다.',
    content: '임대차 계약 종료일 이후 임대인이 보증금을 반환하지 않으면 임차인은 법정이자(연 5%) 또는 약정이자를 청구할 수 있습니다. 내용증명 발송 후 반환 요청을 공식화하는 것이 좋으며, 지급명령 신청도 가능합니다.',
    relatedLaw: '민법 제379조, 제387조',
  },
  {
    id: 'l16',
    title: '집주인 변경 시 임차인 보호',
    category: '임대인',
    summary: '집이 팔려도 전입신고와 확정일자를 받은 임차인은 보호됩니다.',
    content: '전입신고 + 점유를 갖춘 임차인은 집이 매매되더라도 새 집주인에게 대항할 수 있습니다. 단, 이 대항력은 전입신고 다음 날 0시부터 효력이 발생하므로 계약 당일 바로 신고하는 것이 중요합니다.',
    relatedLaw: '주택임대차보호법 제3조 제4항',
  },
  {
    id: 'l17',
    title: '깡통전세 판단 기준',
    category: '보증금',
    summary: '매매가 대비 전세보증금 + 선순위 채권 합계가 80% 초과 시 깡통전세입니다.',
    content: '깡통전세란 집값 하락 시 보증금을 돌려받지 못할 수 있는 전세 계약을 말합니다. (전세보증금 + 선순위 근저당) ÷ 매매가 × 100이 80%를 초과하면 위험 구간입니다. 빌라·오피스텔은 시세 파악이 어려워 더욱 주의가 필요합니다.',
    relatedLaw: 'HUG 전세보증보험 인수 기준',
  },
  {
    id: 'l18',
    title: '내용증명 발송 방법',
    category: '분쟁',
    summary: '보증금 미반환 시 내용증명을 통해 법적 대응의 첫 단계를 밟을 수 있습니다.',
    content: '내용증명은 우체국에서 발송하거나 온라인 우체국 사이트에서 전자발송이 가능합니다. 보증금 반환 요청 내용을 기재하고, 반환 기한을 명시해야 합니다. 내용증명 자체가 법적 효력을 갖는 것은 아니지만, 이후 소송 시 중요한 증거가 됩니다.',
    relatedLaw: '우편법 시행규칙 제25조',
  },
]
