import { Property, LawItem } from './types'

export const properties: Property[] = [
  {
    id: 'p1',
    address: '서울시 마포구 서교동 123-4',
    buildingName: '서교 하이츠',
    type: '빌라',
    floor: '3층',
    area: 33,
    deposit: 15000,
    monthlyRent: null,
    salePrice: 22000,
    leaseRatio: 68,
    risk: '안전',
    mortgage: 3000,
    seizure: false,
    ownerTax: false,
    builtYear: 2018,
    images: ['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=600&q=80'],
    description: '마포구 중심에 위치한 깔끔한 빌라. 지하철 2호선 홍대입구역 도보 10분.',
  },
  {
    id: 'p2',
    address: '서울시 강남구 역삼동 456-7',
    buildingName: '역삼 파크뷰',
    type: '오피스텔',
    floor: '12층',
    area: 26,
    deposit: 30000,
    monthlyRent: null,
    salePrice: 35000,
    leaseRatio: 85,
    risk: '위험',
    mortgage: 18000,
    seizure: true,
    ownerTax: false,
    builtYear: 2012,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80'],
    description: '강남구 역삼동 위치. 전세가율 85% 이상으로 주의 필요.',
  },
  {
    id: 'p3',
    address: '서울시 성동구 성수동 789-1',
    buildingName: '성수 어반',
    type: '아파트',
    floor: '7층',
    area: 59,
    deposit: 40000,
    monthlyRent: null,
    salePrice: 72000,
    leaseRatio: 55,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2020,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80'],
    description: '성수동 핫플 중심. 카페거리 도보 5분. 전세가율 안전.',
  },
  {
    id: 'p4',
    address: '서울시 은평구 불광동 321-5',
    buildingName: '불광 그린빌',
    type: '빌라',
    floor: '2층',
    area: 29,
    deposit: 8000,
    monthlyRent: null,
    salePrice: 11000,
    leaseRatio: 72,
    risk: '경고',
    mortgage: 6000,
    seizure: false,
    ownerTax: true,
    builtYear: 2005,
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=80'],
    description: '은평구 불광동. 집주인 세금 체납 이력 있음. 계약 전 확인 필요.',
  },
  {
    id: 'p5',
    address: '서울시 송파구 잠실동 10-3',
    buildingName: '잠실 리버사이드',
    type: '아파트',
    floor: '15층',
    area: 84,
    deposit: 65000,
    monthlyRent: null,
    salePrice: 120000,
    leaseRatio: 54,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2015,
    images: ['https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=600&q=80'],
    description: '잠실 한강뷰 대단지 아파트. 지하철 2·8호선 잠실역 도보 5분. 전세가율 안전.',
  },
  {
    id: 'p6',
    address: '서울시 용산구 이태원동 55-2',
    buildingName: '이태원 힐탑',
    type: '빌라',
    floor: '4층',
    area: 45,
    deposit: 25000,
    monthlyRent: null,
    salePrice: 29000,
    leaseRatio: 86,
    risk: '위험',
    mortgage: 15000,
    seizure: false,
    ownerTax: true,
    builtYear: 2008,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=600&q=80'],
    description: '이태원 언덕 위 빌라. 전세가율 86%, 근저당 과다. 세금 체납 이력 있음.',
  },
  {
    id: 'p7',
    address: '서울시 관악구 신림동 88-1',
    buildingName: '신림 스카이',
    type: '원룸',
    floor: '5층',
    area: 16,
    deposit: 5000,
    monthlyRent: null,
    salePrice: 8000,
    leaseRatio: 62,
    risk: '안전',
    mortgage: 0,
    seizure: false,
    ownerTax: false,
    builtYear: 2019,
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80'],
    description: '신림역 도보 7분. 신축 원룸. 근저당 없음, 깨끗한 등기.',
  },
  {
    id: 'p8',
    address: '서울시 강서구 마곡동 200-5',
    buildingName: '마곡 더퍼스트',
    type: '오피스텔',
    floor: '8층',
    area: 33,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 24000,
    leaseRatio: 75,
    risk: '경고',
    mortgage: 8000,
    seizure: false,
    ownerTax: false,
    builtYear: 2021,
    images: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600&q=80'],
    description: '마곡나루역 도보 3분. LG사이언스파크 인근. 전세가율 75%로 경고 구간.',
  },
  {
    id: 'p9',
    address: '경기도 수원시 영통구 망포동 33-7',
    buildingName: '망포 센트럴파크',
    type: '아파트',
    floor: '11층',
    area: 59,
    deposit: 28000,
    monthlyRent: null,
    salePrice: 48000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 4000,
    seizure: false,
    ownerTax: false,
    builtYear: 2017,
    images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80'],
    description: '망포역 도보 5분. 대단지 아파트. 수원 영통 핵심 입지. 전세가율 안전.',
  },
  {
    id: 'p10',
    address: '경기도 성남시 분당구 정자동 100-2',
    buildingName: '정자 아이파크',
    type: '아파트',
    floor: '20층',
    area: 115,
    deposit: 80000,
    monthlyRent: null,
    salePrice: 130000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 20000,
    seizure: false,
    ownerTax: false,
    builtYear: 2003,
    images: ['https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=600&q=80'],
    description: '분당 정자역 초역세권. 넓은 평형대. 판교 테크노밸리 출퇴근 최적.',
  },
  {
    id: 'p11',
    address: '인천시 연수구 송도동 5-1',
    buildingName: '송도 더샵',
    type: '아파트',
    floor: '25층',
    area: 84,
    deposit: 35000,
    monthlyRent: null,
    salePrice: 55000,
    leaseRatio: 63,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2016,
    images: ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=600&q=80'],
    description: '송도 국제업무지구 중심. 인천1호선 센트럴파크역 도보 3분.',
  },
  {
    id: 'p12',
    address: '서울시 노원구 상계동 777-3',
    buildingName: '상계 현대아파트',
    type: '아파트',
    floor: '6층',
    area: 49,
    deposit: 22000,
    monthlyRent: null,
    salePrice: 26000,
    leaseRatio: 84,
    risk: '위험',
    mortgage: 12000,
    seizure: true,
    ownerTax: false,
    builtYear: 1992,
    images: ['https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=600&q=80'],
    description: '상계역 인근 구축 아파트. 전세가율 84%, 압류 이력 있음. 계약 전 등기 확인 필수.',
  },
  {
    id: 'p13',
    address: '서울시 동작구 사당동 44-9',
    buildingName: '사당 e편한세상',
    type: '아파트',
    floor: '9층',
    area: 59,
    deposit: 32000,
    monthlyRent: null,
    salePrice: 58000,
    leaseRatio: 55,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2014,
    images: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80'],
    description: '4호선·2호선 환승 사당역 도보 3분. 학원가 인근. 전세가율 55% 안전.',
  },
  {
    id: 'p14',
    address: '서울시 중구 신당동 22-1',
    buildingName: '신당 롯데캐슬',
    type: '아파트',
    floor: '18층',
    area: 84,
    deposit: 55000,
    monthlyRent: null,
    salePrice: 82000,
    leaseRatio: 67,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2011,
    images: ['https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80'],
    description: '2·6호선 신당역 도보 5분. 남산뷰 고층. 주변 편의시설 풍부.',
  },
  {
    id: 'p15',
    address: '서울시 강북구 미아동 13-4',
    buildingName: '미아 삼성래미안',
    type: '아파트',
    floor: '4층',
    area: 49,
    deposit: 19000,
    monthlyRent: null,
    salePrice: 22000,
    leaseRatio: 86,
    risk: '위험',
    mortgage: 9000,
    seizure: false,
    ownerTax: true,
    builtYear: 1999,
    images: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80'],
    description: '전세가율 86% 위험 구간. 집주인 세금 체납 이력 있음. 계약 시 각별한 주의 필요.',
  },
  {
    id: 'p16',
    address: '경기도 고양시 일산동구 장항동 100-1',
    buildingName: '일산 위브더제니스',
    type: '아파트',
    floor: '30층',
    area: 115,
    deposit: 45000,
    monthlyRent: null,
    salePrice: 75000,
    leaseRatio: 60,
    risk: '안전',
    mortgage: 8000,
    seizure: false,
    ownerTax: false,
    builtYear: 2010,
    images: ['https://images.unsplash.com/photo-1549517045-bc93de075e53?w=600&q=80'],
    description: '킨텍스 인근 초고층 아파트. GTX-A 킨텍스역 개통 예정. 전세가율 안전.',
  },
  {
    id: 'p17',
    address: '경기도 용인시 수지구 죽전동 55-3',
    buildingName: '죽전 푸르지오',
    type: '아파트',
    floor: '13층',
    area: 84,
    deposit: 38000,
    monthlyRent: null,
    salePrice: 62000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 6000,
    seizure: false,
    ownerTax: false,
    builtYear: 2006,
    images: ['https://images.unsplash.com/photo-1626178793926-22b28830aa30?w=600&q=80'],
    description: '신분당선 죽전역 도보 8분. 단국대학교 인근. 학군 우수.',
  },
  {
    id: 'p18',
    address: '서울시 강동구 천호동 200-7',
    buildingName: '천호 한양수자인',
    type: '오피스텔',
    floor: '10층',
    area: 29,
    deposit: 14000,
    monthlyRent: null,
    salePrice: 17000,
    leaseRatio: 82,
    risk: '위험',
    mortgage: 10000,
    seizure: true,
    ownerTax: false,
    builtYear: 2013,
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&q=80'],
    description: '5·8호선 천호역 도보 2분. 전세가율 82%, 근저당 과다, 압류 이력 있음.',
  },
  {
    id: 'p19',
    address: '부산시 해운대구 우동 33-5',
    buildingName: '해운대 아이파크',
    type: '아파트',
    floor: '22층',
    area: 130,
    deposit: 60000,
    monthlyRent: null,
    salePrice: 110000,
    leaseRatio: 54,
    risk: '안전',
    mortgage: 15000,
    seizure: false,
    ownerTax: false,
    builtYear: 2011,
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80'],
    description: '해운대 해수욕장 도보 5분. 마린시티 초고층 오션뷰. 부산 최고 입지.',
  },
  {
    id: 'p20',
    address: '대구시 수성구 범어동 77-2',
    buildingName: '범어 SK뷰',
    type: '아파트',
    floor: '16층',
    area: 84,
    deposit: 30000,
    monthlyRent: null,
    salePrice: 52000,
    leaseRatio: 57,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2009,
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=80'],
    description: '대구 최고 학군 수성구. 범어역 도보 6분. 전세가율 안전.',
  },
  {
    id: 'p21',
    address: '서울시 광진구 화양동 33-8',
    buildingName: '화양 더클래스',
    type: '오피스텔',
    floor: '9층',
    area: 30,
    deposit: 16000,
    monthlyRent: null,
    salePrice: 20000,
    leaseRatio: 80,
    risk: '위험',
    mortgage: 9000,
    seizure: false,
    ownerTax: false,
    builtYear: 2016,
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80'],
    description: '건대입구역 도보 5분. 전세가율 80% 위험 구간. 근저당 금액 확인 필요.',
  },
  {
    id: 'p22',
    address: '서울시 서대문구 연희동 55-12',
    buildingName: '연희 파크하임',
    type: '빌라',
    floor: '2층',
    area: 42,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 29000,
    leaseRatio: 62,
    risk: '안전',
    mortgage: 2000,
    seizure: false,
    ownerTax: false,
    builtYear: 2020,
    images: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=80'],
    description: '연희동 조용한 주택가. 신축 빌라. 홍대·신촌 접근성 우수. 근저당 최소.',
  },
  {
    id: 'p23',
    address: '경기도 남양주시 다산동 200-3',
    buildingName: '다산 자이',
    type: '아파트',
    floor: '14층',
    area: 84,
    deposit: 32000,
    monthlyRent: null,
    salePrice: 55000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 5000,
    seizure: false,
    ownerTax: false,
    builtYear: 2019,
    images: ['https://images.unsplash.com/photo-1600047508788-786f3865b8f4?w=600&q=80'],
    description: '경의중앙선 도농역 도보 10분. 대단지 신축. 다산신도시 중심.',
  },
  {
    id: 'p24',
    address: '서울시 동대문구 답십리동 44-7',
    buildingName: '답십리 래미안',
    type: '아파트',
    floor: '5층',
    area: 59,
    deposit: 29000,
    monthlyRent: null,
    salePrice: 37000,
    leaseRatio: 78,
    risk: '경고',
    mortgage: 7000,
    seizure: false,
    ownerTax: false,
    builtYear: 2007,
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80'],
    description: '5호선 답십리역 도보 3분. 전세가율 78% 경고 구간.',
  },
  {
    id: 'p25',
    address: '대전시 유성구 봉명동 10-2',
    buildingName: '봉명 센트럴시티',
    type: '아파트',
    floor: '11층',
    area: 84,
    deposit: 22000,
    monthlyRent: null,
    salePrice: 38000,
    leaseRatio: 57,
    risk: '안전',
    mortgage: 4000,
    seizure: false,
    ownerTax: false,
    builtYear: 2013,
    images: ['https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=600&q=80'],
    description: '카이스트·충남대 인근. 유성온천 도보 10분. 전세가율 안전.',
  },
  {
    id: 'p26',
    address: '서울시 영등포구 당산동 88-3',
    buildingName: '당산 e편한세상',
    type: '아파트',
    floor: '8층',
    area: 59,
    deposit: 34000,
    monthlyRent: null,
    salePrice: 60000,
    leaseRatio: 56,
    risk: '안전',
    mortgage: 6000,
    seizure: false,
    ownerTax: false,
    builtYear: 2012,
    images: ['https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=80'],
    description: '2·5호선 환승 당산역 도보 4분. 여의도 업무지구 접근성 최고.',
  },
  {
    id: 'p27',
    address: '경기도 안양시 동안구 평촌동 33-1',
    buildingName: '평촌 어바인퍼스트',
    type: '아파트',
    floor: '19층',
    area: 115,
    deposit: 48000,
    monthlyRent: null,
    salePrice: 78000,
    leaseRatio: 61,
    risk: '안전',
    mortgage: 10000,
    seizure: false,
    ownerTax: false,
    builtYear: 2008,
    images: ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=600&q=80'],
    description: '평촌 학원가 중심. 4호선 범계역 도보 5분. 학군 최우수.',
  },
  {
    id: 'p28',
    address: '서울시 강남구 개포동 111-5',
    buildingName: '개포 디에이치',
    type: '아파트',
    floor: '12층',
    area: 84,
    deposit: 90000,
    monthlyRent: null,
    salePrice: 160000,
    leaseRatio: 56,
    risk: '안전',
    mortgage: 20000,
    seizure: false,
    ownerTax: false,
    builtYear: 2022,
    images: ['https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=600&q=80'],
    description: '개포 재건축 신축. 강남권 최신 시설. 3호선 대청역 도보 7분.',
  },
  {
    id: 'p29',
    address: '서울시 금천구 시흥동 22-9',
    buildingName: '시흥 한라비발디',
    type: '아파트',
    floor: '3층',
    area: 49,
    deposit: 18000,
    monthlyRent: null,
    salePrice: 21000,
    leaseRatio: 85,
    risk: '위험',
    mortgage: 10000,
    seizure: true,
    ownerTax: false,
    builtYear: 2001,
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80'],
    description: '전세가율 85% 위험 구간. 압류 이력 있음. 계약 전 등기부등본 필수 확인.',
  },
  {
    id: 'p30',
    address: '경기도 하남시 미사동 100-8',
    buildingName: '미사 강변 센트럴자이',
    type: '아파트',
    floor: '17층',
    area: 84,
    deposit: 40000,
    monthlyRent: null,
    salePrice: 68000,
    leaseRatio: 58,
    risk: '안전',
    mortgage: 7000,
    seizure: false,
    ownerTax: false,
    builtYear: 2018,
    images: ['https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=600&q=80'],
    description: '5호선 미사역 도보 5분. 한강뷰 대단지. 미사강변도시 핵심 입지.',
  },
]

export const laws: LawItem[] = [
  {
    id: 'l1',
    title: '전세보증금 반환 의무',
    category: '보증금',
    summary: '임대차 계약 종료 시 집주인은 보증금을 반환해야 합니다.',
    content: '임대인은 임대차 계약이 종료된 경우 임차인에게 보증금을 반환할 의무가 있습니다. 반환하지 않을 경우 임차인은 임차권등기명령을 신청하거나 보증금반환청구소송을 제기할 수 있습니다.',
    relatedLaw: '주택임대차보호법 제3조의3',
  },
  {
    id: 'l2',
    title: '전입신고 및 확정일자',
    category: '임차인',
    summary: '전입신고와 확정일자를 받으면 보증금이 법적으로 보호됩니다.',
    content: '임차인이 전입신고를 하고 확정일자를 받으면 대항력과 우선변제권이 생깁니다. 이로써 건물이 경매에 넘어가더라도 보증금을 우선 돌려받을 수 있습니다.',
    relatedLaw: '주택임대차보호법 제3조, 제3조의2',
  },
  {
    id: 'l3',
    title: '임대차 계약갱신 청구권',
    category: '계약',
    summary: '임차인은 1회에 한해 계약 갱신을 요구할 수 있습니다.',
    content: '2020년 7월 31일부터 시행된 계약갱신청구권제도에 따라 임차인은 최초 계약 만료 시 1회에 한해 2년 연장을 요구할 수 있습니다. 임대인은 정당한 사유 없이 이를 거부할 수 없습니다.',
    relatedLaw: '주택임대차보호법 제6조의3',
  },
  {
    id: 'l4',
    title: '전세가율 위험 기준',
    category: '보증금',
    summary: '전세가율 80% 이상은 깡통전세 위험 구간입니다.',
    content: '전세가율(매매가 대비 전세가 비율)이 80% 이상이면 집값 하락 시 보증금을 돌려받지 못할 위험이 있습니다. 일반적으로 70% 이하를 안전 구간으로 봅니다.',
    relatedLaw: '주택도시보증공사(HUG) 전세보증보험 기준',
  },
  {
    id: 'l5',
    title: '근저당 설정 확인',
    category: '계약',
    summary: '계약 전 등기부등본을 열람해 근저당 여부를 반드시 확인하세요.',
    content: '등기부등본의 을구에서 근저당 설정 금액을 확인할 수 있습니다. 근저당 금액 + 전세보증금이 매매가의 80%를 초과하면 위험합니다. 대법원 인터넷등기소에서 열람 가능합니다.',
    relatedLaw: '부동산등기법 제75조',
  },
  {
    id: 'l6',
    title: '임대인 세금 체납 확인',
    category: '임대인',
    summary: '집주인의 세금 체납 여부를 계약 전에 확인할 수 있습니다.',
    content: '2023년부터 임차인은 임대인의 동의 없이도 관할 세무서에서 임대인의 미납 국세 열람이 가능합니다. 세금 체납 시 국가가 보증금보다 우선 변제를 받을 수 있어 위험합니다.',
    relatedLaw: '국세징수법 제109조',
  },
  {
    id: 'l7',
    title: '전세보증보험 가입 방법',
    category: '보증금',
    summary: 'HUG 또는 SGI서울보증에서 전세보증보험에 가입하면 보증금을 보호받을 수 있습니다.',
    content: '전세보증보험은 임대차 계약 종료 후 집주인이 보증금을 반환하지 않을 경우 보증기관이 대신 지급하는 상품입니다. HUG(주택도시보증공사)와 SGI서울보증에서 가입 가능하며, 전세가율 90% 이하 매물에 한해 가입이 가능합니다. 보험료는 보증금의 약 0.1~0.4% 수준입니다.',
    relatedLaw: '주택도시기금법 제16조',
  },
  {
    id: 'l8',
    title: '묵시적 갱신',
    category: '계약',
    summary: '계약 만료 후 아무 의사 표시가 없으면 동일 조건으로 자동 연장됩니다.',
    content: '임대차 계약 만료 2개월 전까지 임대인 또는 임차인이 갱신 거절 의사를 표시하지 않으면 이전 계약과 동일한 조건으로 묵시적으로 갱신됩니다. 묵시적 갱신 후에는 임차인이 언제든지 3개월 전 통보로 계약 해지가 가능합니다.',
    relatedLaw: '주택임대차보호법 제6조',
  },
  {
    id: 'l9',
    title: '전세사기 피해자 지원',
    category: '분쟁',
    summary: '전세사기 피해자는 정부 지원 프로그램을 통해 법적·금융적 도움을 받을 수 있습니다.',
    content: '2023년 전세사기피해자 지원 및 주거안정에 관한 특별법이 시행되었습니다. 피해자는 경공매 유예, 저금리 대출, 공공임대 우선 입주 등의 혜택을 받을 수 있습니다. 지원 신청은 주거안정지원센터 또는 LH공사를 통해 가능합니다.',
    relatedLaw: '전세사기피해자 지원 및 주거안정에 관한 특별법',
  },
  {
    id: 'l10',
    title: '임차권등기명령 신청',
    category: '임차인',
    summary: '계약 종료 후 보증금을 받지 못했다면 임차권등기명령을 신청하세요.',
    content: '임대차 계약이 종료됐는데 보증금을 돌려받지 못한 경우, 임차인은 관할 법원에 임차권등기명령을 신청할 수 있습니다. 등기가 완료되면 이사를 나가더라도 대항력과 우선변제권이 유지됩니다. 신청 비용은 약 5천 원 수준입니다.',
    relatedLaw: '주택임대차보호법 제3조의3',
  },
  {
    id: 'l11',
    title: '월세 전환 시 전환율 제한',
    category: '계약',
    summary: '전세를 월세로 전환할 때 법정 전환율을 초과할 수 없습니다.',
    content: '보증금 일부를 월세로 전환할 경우, 법정 전환율(현행 연 10% 또는 한국은행 기준금리 + 2% 중 낮은 값) 이하로만 전환이 가능합니다. 이를 초과한 월세는 무효이며 초과분을 반환받을 수 있습니다.',
    relatedLaw: '주택임대차보호법 제7조의2',
  },
  {
    id: 'l12',
    title: '소액임차인 최우선변제권',
    category: '보증금',
    summary: '일정 금액 이하 보증금은 경매 시 최우선으로 변제받을 수 있습니다.',
    content: '소액임차인은 경매 낙찰가의 일정 비율에서 다른 채권자보다 우선하여 보증금 일부를 변제받을 수 있습니다. 서울 기준 보증금 1억 6,500만 원 이하 임차인은 최대 5,500만 원까지 최우선 변제됩니다. 단, 전입신고와 점유 요건을 갖춰야 합니다.',
    relatedLaw: '주택임대차보호법 제8조',
  },
  {
    id: 'l13',
    title: '임대인 동의 없는 전대차 금지',
    category: '임차인',
    summary: '집주인 동의 없이 집을 다시 세주는 것은 불법입니다.',
    content: '임차인은 임대인의 동의 없이 임차한 주택을 제3자에게 전대(재임대)할 수 없습니다. 무단 전대 시 임대인은 계약을 해지할 수 있으며, 임차인은 손해배상 책임을 질 수 있습니다.',
    relatedLaw: '민법 제629조',
  },
  {
    id: 'l14',
    title: '계약서 특약 사항 작성 요령',
    category: '계약',
    summary: '특약 사항을 꼼꼼히 기재하면 분쟁 발생 시 유리한 위치에 설 수 있습니다.',
    content: '계약서 특약란에는 수리 범위, 원상복구 기준, 보증금 반환 시기, 중도 해지 조건 등을 구체적으로 기재해야 합니다. "협의 후 결정" 같은 모호한 표현은 피하고, 날짜와 금액을 명확히 적어야 합니다. 특약은 법정 기준보다 임차인에게 유리한 내용으로 작성할 수 있습니다.',
    relatedLaw: '주택임대차보호법 제10조(강행규정)',
  },
  {
    id: 'l15',
    title: '보증금 반환 지연 시 이자 청구',
    category: '보증금',
    summary: '계약 만료 후 보증금을 늦게 돌려받으면 이자를 청구할 수 있습니다.',
    content: '임대차 계약 종료일 이후 임대인이 보증금을 반환하지 않으면 임차인은 법정이자(연 5%) 또는 약정이자를 청구할 수 있습니다. 내용증명 발송 후 반환 요청을 공식화하는 것이 좋으며, 지급명령 신청도 가능합니다.',
    relatedLaw: '민법 제379조, 제387조',
  },
  {
    id: 'l16',
    title: '집주인 변경 시 임차인 보호',
    category: '임대인',
    summary: '집이 팔려도 전입신고와 확정일자를 받은 임차인은 보호됩니다.',
    content: '전입신고 + 점유를 갖춘 임차인은 집이 매매되더라도 새 집주인에게 대항할 수 있습니다. 단, 이 대항력은 전입신고 다음 날 0시부터 효력이 발생하므로 계약 당일 바로 신고하는 것이 중요합니다.',
    relatedLaw: '주택임대차보호법 제3조 제4항',
  },
  {
    id: 'l17',
    title: '깡통전세 판단 기준',
    category: '보증금',
    summary: '매매가 대비 전세보증금 + 선순위 채권 합계가 80% 초과 시 깡통전세입니다.',
    content: '깡통전세란 집값 하락 시 보증금을 돌려받지 못할 수 있는 전세 계약을 말합니다. (전세보증금 + 선순위 근저당) ÷ 매매가 × 100이 80%를 초과하면 위험 구간입니다. 빌라·오피스텔은 시세 파악이 어려워 더욱 주의가 필요합니다.',
    relatedLaw: 'HUG 전세보증보험 인수 기준',
  },
  {
    id: 'l18',
    title: '내용증명 발송 방법',
    category: '분쟁',
    summary: '보증금 미반환 시 내용증명을 통해 법적 대응의 첫 단계를 밟을 수 있습니다.',
    content: '내용증명은 우체국에서 발송하거나 온라인 우체국 사이트에서 전자발송이 가능합니다. 보증금 반환 요청 내용을 기재하고, 반환 기한을 명시해야 합니다. 내용증명 자체가 법적 효력을 갖는 것은 아니지만, 이후 소송 시 중요한 증거가 됩니다.',
    relatedLaw: '우편법 시행규칙 제25조',
  },

  // ── 등기·권리분석 ──────────────────────────────────────────
  {
    id: 'l19',
    title: '신탁등기란?',
    category: '계약',
    summary: '등기부 갑구에 신탁 문구가 있으면 집주인이 아닌 수탁자 동의가 필요합니다.',
    content: '신탁등기란 소유자(위탁자)가 부동산을 신탁회사(수탁자)에 법률상 이전한 상태입니다. 이 경우 실제 임대계약은 수탁자(신탁사)와 체결하거나, 수탁자의 동의서를 받아야 유효합니다. 신탁 동의 없이 위탁자와 계약하면 계약 자체가 무효가 될 수 있어 매우 위험합니다. 등기부 갑구에서 "신탁" 문구를 반드시 확인하세요.',
    relatedLaw: '신탁법 제3조, 주택임대차보호법 제3조',
  },
  {
    id: 'l20',
    title: '가등기의 위험성',
    category: '계약',
    summary: '소유권이전청구권 가등기가 있으면 집주인이 바뀔 수 있어요.',
    content: '가등기는 본등기를 하기 위한 순위 보전 수단입니다. 가등기권자가 본등기를 실행하면 집주인이 바뀌고, 기존 임차인의 전입일보다 가등기일이 앞서면 임차인은 새 소유자에게 대항하지 못할 수 있습니다. 계약 전 등기부 갑구에서 가등기 유무를 반드시 확인하세요.',
    relatedLaw: '부동산등기법 제88조, 민법 제187조',
  },
  {
    id: 'l21',
    title: '전세권 설정과 전입신고 비교',
    category: '임차인',
    summary: '전세권 설정등기는 전입신고보다 강력하지만 비용이 더 들어요.',
    content: '전세권 설정등기는 등기부에 직접 권리가 기재되어 별도의 전입신고 없이도 대항력과 우선변제권이 생깁니다. 집주인이 전입신고를 거부하는 경우, 또는 법인·외국인 임차인의 경우 유리합니다. 단, 설정 비용(보증금의 약 0.2%)이 추가로 들고 집주인의 동의가 필요합니다.',
    relatedLaw: '민법 제303조~제319조, 부동산등기법',
  },
  {
    id: 'l22',
    title: '근저당 우선순위와 배당 계산',
    category: '보증금',
    summary: '내 전입신고일보다 앞선 근저당이 경매 시 먼저 배당됩니다.',
    content: '경매 배당 순서는 설정일자 기준으로 결정됩니다. 내 전입신고일(+확정일자) 이전에 설정된 근저당은 선순위로, 내 보증금보다 먼저 배당됩니다. 반대로 내 전입신고 이후에 설정된 근저당은 후순위입니다. 계약 시점의 등기부를 기준으로 선순위 근저당 총액을 확인하고, 이를 보증금 + 선순위 근저당이 매매가의 70% 이하인지 검토하세요.',
    relatedLaw: '민법 제368조, 주택임대차보호법 제3조의2',
  },
  {
    id: 'l23',
    title: '가압류·압류의 차이',
    category: '계약',
    summary: '압류는 확정된 채권, 가압류는 소송 중인 채권으로 집이 경매에 넘어갈 수 있어요.',
    content: '압류는 법원의 확정 판결 또는 집행권원으로 재산을 강제 집행하는 것입니다. 가압류는 소송이 진행 중인 상태에서 미리 재산을 동결하는 조치입니다. 등기부에 압류·가압류가 있으면 해당 채권자가 경매를 신청할 수 있어 임차인에게 매우 위험합니다. 을구뿐 아니라 갑구도 반드시 확인하세요.',
    relatedLaw: '민사집행법 제276조, 제291조',
  },

  // ── 계약 실전 ──────────────────────────────────────────────
  {
    id: 'l24',
    title: '계약금 이중계약 사기 예방',
    category: '계약',
    summary: '계약금을 입금하기 전 등기부등본을 재확인하고 집주인 신원을 반드시 검증하세요.',
    content: '계약금 사기는 집주인을 사칭하거나 이미 계약된 매물에 이중으로 계약금을 받는 방식으로 이루어집니다. 계약 당일 계약금 입금 직전에 등기부등본을 재열람하고, 집주인 신분증과 등기부상 소유자를 대조하세요. 계좌이체 시 수취인명이 소유자와 일치하는지 확인하는 것도 중요합니다.',
    relatedLaw: '형법 제347조(사기죄)',
  },
  {
    id: 'l25',
    title: '계약금 반환 (해약금)',
    category: '계약',
    summary: '임차인이 계약을 파기하면 계약금을 포기, 임대인이 파기하면 배액 반환해야 해요.',
    content: '계약금은 해약금의 성질을 가집니다. 임차인(교부자)이 계약을 해제하면 계약금을 포기해야 하고, 임대인(수령자)이 계약을 해제하면 계약금의 2배를 반환해야 합니다. 단, 이행의 착수(잔금 지급 또는 집 인도) 후에는 해약금에 의한 해제가 불가합니다.',
    relatedLaw: '민법 제565조',
  },
  {
    id: 'l26',
    title: '중도 해지 시 임차인 권리',
    category: '계약',
    summary: '계약 기간 중 임차인이 먼저 나가야 한다면 후임 임차인을 구해 피해를 최소화하세요.',
    content: '계약 기간 중 임차인이 일방적으로 해지하면 임대인에게 손해배상 책임이 생길 수 있습니다. 그러나 임대인이 동의하거나, 후임 임차인을 직접 구해오는 방식으로 원만히 해결하는 경우가 많습니다. 묵시적 갱신된 경우에는 언제든 3개월 전 통보로 해지 가능합니다.',
    relatedLaw: '주택임대차보호법 제6조의2',
  },
  {
    id: 'l27',
    title: '묵시적 갱신 해지 통보 타이밍',
    category: '계약',
    summary: '계약 만료 2~6개월 전 사이에 갱신 거절 통보를 해야 효력이 있습니다.',
    content: '임대인은 계약 만료 6개월~2개월 전 사이에 갱신 거절 의사를 통보해야 합니다. 임차인은 만료 2개월 전까지 통보해야 합니다. 이 기간 내 통보하지 않으면 묵시적으로 갱신됩니다. 묵시적 갱신 후에는 임차인만 3개월 전 통보로 해지할 수 있으며, 임대인은 정당한 사유 없이 해지를 요구할 수 없습니다.',
    relatedLaw: '주택임대차보호법 제6조 제1항',
  },
  {
    id: 'l28',
    title: '필수 특약 문구 모음',
    category: '계약',
    summary: '계약서 특약란에 꼭 넣어야 할 문구들을 미리 준비하세요.',
    content: '① 잔금일 당일 등기부등본 이상 없을 시 잔금 지급 조건 ② 전세보증보험 가입 동의 특약 ③ 계약 후 집주인이 근저당 추가 설정 금지 ④ 임대차 계약 종료 시 즉시 보증금 반환 ⑤ 인테리어·수리 범위 및 원상복구 기준 명시 ⑥ 확정일자·전입신고 당일 처리 동의. 이 조항들은 분쟁 발생 시 임차인을 보호하는 핵심 장치입니다.',
    relatedLaw: '주택임대차보호법 제10조',
  },

  // ── 경매·배당 ──────────────────────────────────────────────
  {
    id: 'l29',
    title: '배당요구 신청 방법',
    category: '분쟁',
    summary: '집이 경매에 넘어가면 배당요구 종기일 전까지 반드시 신청해야 해요.',
    content: '임차주택이 경매에 넘어가면 법원에서 배당요구 종기일을 공고합니다. 이 기일 전까지 확정일자부 임차인은 배당요구서를 제출해야 보증금을 배당받을 수 있습니다. 법원 경매 공고(법원경매정보 사이트)를 통해 종기일을 확인하고, 기일을 놓치면 배당에서 제외됩니다.',
    relatedLaw: '민사집행법 제88조',
  },
  {
    id: 'l30',
    title: '경매 낙찰 후 명도',
    category: '분쟁',
    summary: '경매로 집이 팔린 후 새 소유자가 퇴거를 요구할 수 있어요.',
    content: '경매 낙찰 후 새 소유자는 임차인에게 명도(퇴거)를 요구할 수 있습니다. 단, 대항력 있는 임차인(전입신고 + 선순위)은 보증금을 돌려받을 때까지 퇴거를 거부할 수 있습니다. 대항력이 없는 임차인은 명도 요구에 따라야 하므로, 배당요구와 보증금 회수를 우선 진행해야 합니다.',
    relatedLaw: '민사집행법 제136조',
  },
  {
    id: 'l31',
    title: '배당이의 신청',
    category: '분쟁',
    summary: '배당 결과가 부당하다면 배당기일에 이의를 제기할 수 있습니다.',
    content: '배당기일에 배당표가 확정되기 전까지 이해관계인은 배당이의를 제기할 수 있습니다. 이의가 받아들여지지 않으면 배당기일로부터 1주일 이내에 배당이의의 소를 제기해야 합니다. 예를 들어 세금 체납으로 잘못 우선 배당된 경우, 근저당 설정 무효를 주장하는 경우 등에 활용됩니다.',
    relatedLaw: '민사집행법 제151조, 제154조',
  },
  {
    id: 'l32',
    title: '소액임차인 배당 계산 방법',
    category: '보증금',
    summary: '지역별 소액 기준과 최우선 배당액을 미리 계산해두세요.',
    content: '소액임차인 최우선변제 기준은 지역마다 다릅니다. 2024년 기준: 서울 보증금 1억 6,500만 원 이하 → 최대 5,500만 원, 수도권(과밀억제권역) 1억 4,500만 원 이하 → 4,800만 원, 광역시 8,500만 원 이하 → 2,800만 원, 기타 지역 7,500만 원 이하 → 2,500만 원. 전입신고 + 점유 요건을 갖춰야 합니다.',
    relatedLaw: '주택임대차보호법 제8조, 시행령 제10조·제11조',
  },

  // ── 법적 절차 ──────────────────────────────────────────────
  {
    id: 'l33',
    title: '지급명령 신청',
    category: '분쟁',
    summary: '소송 없이 빠르게 보증금을 받을 수 있는 간이 절차예요.',
    content: '지급명령은 법원에 신청서를 제출하면 상대방 심문 없이 지급 명령을 내리는 절차입니다. 보증금 규모와 관계없이 신청 가능하며, 2주 이내에 결정이 납니다. 채무자(집주인)가 이의를 신청하지 않으면 확정 판결과 동일한 효력이 생깁니다. 소송보다 빠르고 비용이 저렴합니다.',
    relatedLaw: '민사소송법 제462조~제474조',
  },
  {
    id: 'l34',
    title: '소액심판 제도',
    category: '분쟁',
    summary: '3,000만 원 이하 보증금 분쟁은 소액사건심판으로 빠르게 해결할 수 있어요.',
    content: '소액사건심판은 소송가액 3,000만 원 이하 사건에 대해 간이하고 신속하게 처리하는 절차입니다. 1심 판결이 최종 확정되는 경우가 많아 빠른 해결이 가능합니다. 법률 전문 지식 없이도 직접 신청할 수 있으며, 대한법률구조공단의 무료 도움을 받을 수 있습니다.',
    relatedLaw: '소액사건심판법 제1조·제2조',
  },
  {
    id: 'l35',
    title: '전세사기 형사 고소 (사기죄)',
    category: '분쟁',
    summary: '고의적인 전세사기는 형사 고소로 집주인을 처벌받게 할 수 있습니다.',
    content: '집주인이 처음부터 보증금을 돌려줄 의사 없이 계약한 경우, 또는 이미 과다한 채무로 보증금 반환이 불가능하다는 것을 알면서 계약한 경우 사기죄가 성립할 수 있습니다. 경찰서 또는 검찰청에 고소장을 제출하고, 계약서·이체 내역·문자 등을 증거로 제출하세요. 형사 절차와 민사 절차는 병행 진행이 가능합니다.',
    relatedLaw: '형법 제347조 (10년 이하 징역 또는 2,000만 원 이하 벌금)',
  },
  {
    id: 'l36',
    title: '임차권등기 심화 — 효력과 한계',
    category: '임차인',
    summary: '임차권등기 후에도 새 임차인은 보증금 우선순위에서 밀릴 수 있어요.',
    content: '임차권등기명령이 완료되면 이사를 나가도 대항력·우선변제권이 유지됩니다. 그러나 등기 후 새로 입주하는 임차인은 임차권등기의 존재를 알면서 계약한 것이므로 자신의 보증금을 기존 임차권등기 이후로 배당받게 됩니다. 임차권등기가 설정된 집에 새로 들어가는 것은 매우 위험합니다.',
    relatedLaw: '주택임대차보호법 제3조의3 제5항',
  },
  {
    id: 'l37',
    title: '민사 보전처분 — 가처분',
    category: '분쟁',
    summary: '집주인이 집을 팔려고 할 때 처분금지가처분으로 막을 수 있어요.',
    content: '집주인이 보증금 미반환 상태에서 집을 매각하려는 경우, 임차인은 법원에 처분금지가처분을 신청할 수 있습니다. 가처분이 인용되면 집주인은 해당 부동산을 팔거나 담보로 제공할 수 없게 됩니다. 법원에서 소명자료를 검토 후 수일 내 결정합니다.',
    relatedLaw: '민사집행법 제300조',
  },

  // ── 정부지원 ──────────────────────────────────────────────
  {
    id: 'l38',
    title: '전세사기 피해자 특례대출',
    category: '보증금',
    summary: '피해자는 저금리 긴급 대출로 새 집 보증금 마련이 가능해요.',
    content: '전세사기 피해자로 확인서를 발급받은 경우 다음 대출 혜택이 있습니다. ① 피해자 전용 버팀목 전세자금 대출: 최대 2억 4,000만 원, 연 1~2% ② 긴급 주거 안정 자금: 최대 7,000만 원 ③ LH·HUG를 통한 공공임대 우선 입주. 신청은 LH 마이홈 앱 또는 주거안정지원센터에서 가능합니다.',
    relatedLaw: '전세사기피해자 지원 및 주거안정에 관한 특별법',
  },
  {
    id: 'l39',
    title: 'HUG 전세보증보험 심화',
    category: '보증금',
    summary: '가입 조건·보험료·지급 절차를 미리 알아두면 유사시 빠르게 대응할 수 있어요.',
    content: '가입 조건: 전세가율 90% 이하, 보증금 수도권 7억·지방 5억 이하, 아파트·연립·다세대·오피스텔·단독 해당. 보험료: 보증금의 0.115~0.154%(아파트 기준). 지급 절차: 계약 종료 후 집주인에게 반환 요청 → 미반환 확인 → HUG에 보증금 지급 청구 → HUG가 대신 지급 후 집주인에게 구상권 행사. 가입은 임대차 계약일로부터 전세기간의 1/2이 지나기 전에 해야 합니다.',
    relatedLaw: '주택도시기금법 제16조',
  },
  {
    id: 'l40',
    title: '경·공매 유예 신청',
    category: '분쟁',
    summary: '피해자 확인서가 있으면 경매·공매를 최대 2년 유예받을 수 있어요.',
    content: '전세사기피해자 지원 특별법에 따라 피해자 확인서를 받은 경우 경매·공매 절차의 유예를 신청할 수 있습니다. 유예 기간 동안 강제 퇴거를 막고, 이 기간을 활용해 대출 신청·이주 준비·소송 진행 등을 할 수 있습니다. 신청은 관할 법원(경매) 또는 한국자산관리공사(공매)에 합니다.',
    relatedLaw: '전세사기피해자 지원 및 주거안정에 관한 특별법 제13조',
  },
  {
    id: 'l41',
    title: '주거급여 신청 자격',
    category: '임차인',
    summary: '일정 소득 이하라면 월세 일부를 정부가 지원해줘요.',
    content: '주거급여는 기준 중위소득 48% 이하 가구에게 임차료(월세) 일부를 지원하는 제도입니다. 월 최대 34만 원 (서울 기준 1인 가구)까지 지원받을 수 있으며, 수급자격은 복지로 또는 읍·면·동 주민센터에서 신청할 수 있습니다. 전세 거주자도 해당 요건을 충족하면 신청 가능합니다.',
    relatedLaw: '주거급여법 제7조',
  },
  {
    id: 'l42',
    title: '긴급복지 주거 지원',
    category: '임차인',
    summary: '갑작스러운 주거 위기 상황에서 정부 긴급 지원을 받을 수 있어요.',
    content: '전세사기로 갑자기 집을 잃은 경우 긴급복지 지원을 통해 임시 주거(여관·고시원·임시주거시설)비를 지원받을 수 있습니다. 1회 최대 64만 3,900원(2024년 기준)이며, 4회까지 연장 가능합니다. 주소지 읍·면·동 주민센터 또는 보건복지상담 콜센터 129에서 신청합니다.',
    relatedLaw: '긴급복지지원법 제9조',
  },

  // ── 세금 ──────────────────────────────────────────────────
  {
    id: 'l43',
    title: '집주인 국세 체납 무료 조회',
    category: '세금',
    summary: '2023년부터 임차인은 집주인 동의 없이 세금 체납 여부를 확인할 수 있어요.',
    content: '2023년 4월부터 임차인은 임대인의 동의 없이 관할 세무서(또는 홈택스)에서 임대인의 미납 국세 금액을 열람할 수 있습니다. 임대차 계약 체결 전 또는 계약금 납부 전에 반드시 확인하세요. 국세가 임차인 보증금보다 우선 변제되기 때문에 체납이 있으면 보증금 회수에 큰 영향을 줍니다.',
    relatedLaw: '국세징수법 제109조의2',
  },
  {
    id: 'l44',
    title: '집주인 지방세 체납 확인',
    category: '세금',
    summary: '지방세(재산세·취득세 등) 체납도 보증금 회수에 영향을 줍니다.',
    content: '2023년 개정으로 임차인은 관할 지방자치단체에서 임대인의 지방세 체납 여부도 열람 가능합니다. 재산세·종합부동산세 같은 당해세는 경매 시 근저당보다 우선 변제되는 경우가 있어 임차인에게 불리할 수 있습니다. 계약 전 국세·지방세 체납 여부 모두 확인하는 것이 좋습니다.',
    relatedLaw: '지방세징수법 제7조의2',
  },
  {
    id: 'l45',
    title: '오피스텔 부가가치세 주의',
    category: '세금',
    summary: '업무용 오피스텔 임대 시 부가세가 붙을 수 있으니 계약 전 확인하세요.',
    content: '오피스텔은 용도에 따라 주거용과 업무용으로 구분됩니다. 업무용 오피스텔은 임대료에 부가가치세(10%)가 부과될 수 있으며, 이 경우 임차인이 부담하는 경우가 있습니다. 반면 주거용으로 사용하면 주택임대차보호법의 보호를 받습니다. 계약 전 사용 용도와 부가세 여부를 명확히 확인하세요.',
    relatedLaw: '부가가치세법 제26조, 주택임대차보호법 적용 범위',
  },
  {
    id: 'l46',
    title: '임차인 연말정산 월세 세액공제',
    category: '세금',
    summary: '월세 임차인은 연 최대 112만 원까지 세액공제를 받을 수 있어요.',
    content: '총 급여 7,000만 원 이하 근로자는 월세 지출액의 15~17%를 세액공제 받을 수 있습니다. 연간 월세 납부액 최대 1,000만 원 한도 내에서 공제가 가능합니다. 계약서, 주민등록등본, 월세 이체 내역을 갖춰 연말정산 시 신청하면 됩니다. 전입신고가 되어 있어야 공제 가능합니다.',
    relatedLaw: '소득세법 제95조의2',
  },

  // ── 추가 실전 정보 ─────────────────────────────────────────
  {
    id: 'l47',
    title: '등기부등본 보는 법',
    category: '계약',
    summary: '표제부·갑구·을구 세 파트로 나뉘며 각각 확인해야 할 정보가 다릅니다.',
    content: '등기부등본은 세 파트로 구성됩니다. ① 표제부: 건물 기본정보(소재지, 면적, 용도, 건축년도) ② 갑구: 소유권 관련(현 소유자, 압류·가압류·가등기·신탁 여부) ③ 을구: 소유권 외 권리(근저당권, 전세권 설정 여부 및 금액). 계약 전과 잔금 지급 직전, 총 두 번 발급해 변동 여부를 확인하는 것이 원칙입니다. 대법원 인터넷등기소에서 700원에 발급 가능합니다.',
    relatedLaw: '부동산등기법',
  },
  {
    id: 'l48',
    title: '건축물대장 확인하는 이유',
    category: '계약',
    summary: '무허가 건물이나 위반 건축물은 전세보증보험 가입이 불가합니다.',
    content: '건축물대장에는 건물의 공식 용도와 층수, 면적이 기재됩니다. 등기부상 면적과 다르거나, 용도가 "근린생활시설"로 되어 있는 경우 주거용으로 인정받지 못해 전세보증보험 가입이 불가할 수 있습니다. 위반 건축물(빨간 딱지)은 이행강제금 부과 대상이며, 철거 명령이 내려질 수도 있습니다. 정부24에서 무료 발급 가능합니다.',
    relatedLaw: '건축법 제79조',
  },
  {
    id: 'l49',
    title: '다가구 vs 다세대 차이',
    category: '계약',
    summary: '다가구는 집주인이 1명, 다세대는 각 세대별 별도 소유라 위험도가 달라요.',
    content: '다가구주택은 1동 전체가 한 명의 소유로 등기됩니다. 따라서 경매 시 건물 전체가 낙찰되며, 선순위 임차인이 많을수록 내 보증금 회수 가능성이 낮아집니다. 다세대주택은 각 세대가 독립적으로 등기되므로 다른 세대 임차인의 영향을 받지 않습니다. 다가구는 전입세대 열람을 통해 선순위 임차인을 반드시 확인하세요.',
    relatedLaw: '건축법 제2조, 주택법',
  },
  {
    id: 'l50',
    title: '전세 계약 전 체크리스트 요약',
    category: '계약',
    summary: '계약 전 반드시 확인해야 할 10가지 핵심 사항입니다.',
    content: '① 등기부등본 열람 (갑구·을구 확인) ② 건축물대장 열람 (용도·위반건축물 여부) ③ 집주인 신분증 대조 ④ 임대인 국세·지방세 체납 조회 ⑤ 전세가율 확인 (70% 이하 권장) ⑥ 선순위 근저당 + 보증금 합산 비율 확인 ⑦ 다가구 시 전입세대 열람 ⑧ 전세보증보험 가입 가능 여부 확인 ⑨ 계약서 특약 작성 ⑩ 잔금일 당일 등기부 재확인 후 잔금 지급.',
    relatedLaw: '주택임대차보호법 종합',
  },
  {
    id: 'l51',
    title: '공인중개사 책임과 손해배상',
    category: '계약',
    summary: '공인중개사가 허위·부실 중개로 손해를 끼쳤다면 배상 청구가 가능해요.',
    content: '공인중개사는 중개 행위 시 성실 의무가 있으며, 허위 정보 제공이나 확인 의무 태만으로 임차인에게 손해를 끼쳤다면 민사 손해배상 책임이 있습니다. 공인중개사 사무소는 반드시 공제조합 가입 여부를 확인하고, 중개사 등록증을 열람해 정상 영업 중인지 확인하세요. 피해 시 한국공인중개사협회에 신고할 수 있습니다.',
    relatedLaw: '공인중개사법 제30조',
  },
  {
    id: 'l52',
    title: '대리인과 계약 시 주의사항',
    category: '계약',
    summary: '집주인 대신 대리인이 계약하면 위임장과 인감증명서를 반드시 확인하세요.',
    content: '집주인 본인이 아닌 대리인과 계약할 경우, ① 집주인 인감도장이 날인된 위임장 ② 집주인 인감증명서 ③ 대리인 신분증을 반드시 요구해야 합니다. 가능하다면 집주인에게 직접 전화해 대리 계약 사실을 확인하세요. 위임 없는 대리 계약은 무효가 될 수 있으며, 보증금 반환 의무도 불명확해집니다.',
    relatedLaw: '민법 제114조~제136조(대리)',
  },
  {
    id: 'l53',
    title: '법인 집주인 계약 주의사항',
    category: '임대인',
    summary: '법인이 임대인인 경우 법인 등기부와 대표자 인감을 따로 확인해야 해요.',
    content: '집주인이 법인인 경우 법인 등기부등본(대법원 인터넷등기소)에서 법인 실체 및 대표자를 확인하고, 법인 인감증명서와 법인 인감도장이 날인된 계약서를 요구해야 합니다. 법인은 개인보다 파산·청산 리스크가 높을 수 있으며, 부동산 법인의 경우 세금 문제로 급매 처분되는 경우도 있으므로 재정 상태를 추가로 확인하세요.',
    relatedLaw: '상법 제209조, 민법 제34조',
  },
  {
    id: 'l54',
    title: '전세자금대출과 임대인 동의',
    category: '보증금',
    summary: '전세자금대출을 받으려면 집주인 동의가 필요한 경우가 있어요.',
    content: '은행 전세자금대출을 받을 때 일부 상품은 임대인의 동의 또는 질권 설정이 필요합니다. 특히 HUG·HF 보증부 대출은 보증서 발급 과정에서 임대인 확인이 필요합니다. 계약 전에 이용할 대출 상품을 결정하고, 임대인의 동의 가능 여부를 미리 확인해두는 것이 중요합니다.',
    relatedLaw: '은행법, 주택도시기금법',
  },
  {
    id: 'l55',
    title: '전입신고를 못하는 경우 대안',
    category: '임차인',
    summary: '전입신고가 어렵다면 전세권 설정등기로 보호받을 수 있어요.',
    content: '법인이나 외국인의 경우 주민등록 전입신고가 불가해 일반적인 임차인 보호를 받기 어렵습니다. 이 경우 전세권 설정등기를 통해 대항력과 우선변제권을 확보할 수 있습니다. 개인도 집주인이 전입신고를 방해하거나 다른 사정으로 전입이 어려울 때 전세권 설정이 대안이 됩니다. 비용은 보증금의 약 0.2%(등록세 등 포함)입니다.',
    relatedLaw: '민법 제303조, 주민등록법',
  },
  {
    id: 'l56',
    title: '집주인 사망 시 보증금 처리',
    category: '임대인',
    summary: '집주인이 사망하면 상속인에게 보증금 반환을 청구할 수 있어요.',
    content: '임대인이 사망하면 상속인이 임대인 지위를 승계하며, 보증금 반환 의무도 상속됩니다. 상속인이 상속을 포기하거나 한정승인하는 경우 절차가 복잡해질 수 있습니다. 집주인 사망 사실을 알게 된 즉시 임차권등기명령을 신청하고, 법률 전문가의 도움을 받아 상속인을 특정하고 보증금 반환 청구 절차를 진행하세요.',
    relatedLaw: '민법 제1005조(상속의 포괄 승계), 제1019조',
  },
  {
    id: 'l57',
    title: '역전세 상황 대처법',
    category: '보증금',
    summary: '집값이 올라 전세금을 돌려주기 어려운 집주인에게 대처하는 방법이에요.',
    content: '역전세란 전세가가 매매가를 초과하거나 시세 하락으로 집주인이 보증금을 반환하기 어려운 상황입니다. 이 경우 ① 계약 갱신 시 보증금 감액 협상 ② 임차인이 전세자금대출 재활용 ③ 집주인이 새 임차인 보증금으로 반환 등 방법을 사용합니다. 집주인이 반환 능력이 없다면 즉시 법적 절차(임차권등기·지급명령)를 진행하세요.',
    relatedLaw: '주택임대차보호법 제3조의3',
  },
  {
    id: 'l58',
    title: '전세보증금 분쟁조정위원회 활용',
    category: '분쟁',
    summary: '소송 전 분쟁조정 신청으로 비용과 시간을 절약할 수 있어요.',
    content: '법무부 산하 주택임대차분쟁조정위원회에 분쟁 조정을 신청하면 무료 또는 저렴한 비용으로 조정을 시도할 수 있습니다. 조정 기간은 통상 60일 이내이며, 양측이 합의하면 재판상 화해와 동일한 효력이 생깁니다. 전국 16개 지역 조정위원회 또는 대한법률구조공단(132)을 통해 신청 가능합니다.',
    relatedLaw: '주택임대차보호법 제14조~제29조',
  },
]
